### ISSUE TITLE
[replaying] gmail.com Error Session Died Unexpectedly

### ISSUE THREAD

**Issue by jasonLaster** [WebReplay/webreplay-devtools#237] opened 2020-07-12 14:18 UTC
I've been seeing "Error Session Died Unexpectedly" recently. perhaps because i'm recording many sites at the same time.

gmail - https://webreplay.io/view?id=f2af99f3-6ac0-43e7-82cd-7b680bfcad34
twitter - https://webreplay.io/view?id=5c316be1-080f-4586-8e4b-963d9c156545

**Comment by jasonLaster** [comment] 2020-07-12 14:19
I'm seeing Disconnected as well. what is the difference?

**Comment by bhackett1024** [comment] 2020-07-13 15:25
These both indicate different kinds of server side problems --- "Session died unexpectedly" means that the server side of the current session died, while "Disconnected" means that the server itself died (much more serious), which will kick everyone else off too.  It will automatically restart, though.

**Comment by bhackett1024** [comment] 2020-07-13 18:14
The problem is the same for both of these, and many failures over the last few days.  I think this is fixed now (strange problem that may have been a miscompilation), I haven't been able to reproduce it with the latest build.

gmail: https://webreplay.io/view?id=d8430fbd-ae16-4da7-9adf-50054b1e1c12
twitter: https://webreplay.io/view?id=0928f5fc-fc5c-4d31-8ade-58c9ee3fcd34

**Closed by bhackett1024** 2020-07-13 18:14 UTC
Labels: Replayer, bug
