### ISSUE TITLE
Turn scope mapping on by default

### ISSUE THREAD

**Issue by bhackett1024** [WebReplay/webreplay-devtools#4] opened 2020-05-08 15:01 UTC
In the devtools, scope mapping is an optional feature, as it is really slow.  I feel that scope mapping is an essential feature when debugging production sites with source maps.  The performance issue needs to be fixed and this feature needs to be enabled by default.

**Comment by jasonLaster** [comment] 2020-06-10 00:30
Closing as it is a dupe of #62

**Closed by jasonLaster** 2020-06-10 00:30 UTC
