### ISSUE TITLE
Graphical artifact in frame timeline

### ISSUE THREAD

**Issue by bhackett1024** [WebReplay/webreplay-devtools#155] opened 2020-06-20 21:18 UTC
When the frame timeline is at 100% it looks wrong.
<img width="424" alt="Screen Shot 2020-06-20 at 11 17 03 AM" src="https://user-images.githubusercontent.com/1062578/85211728-b578be00-b2e7-11ea-83ff-9dc75924efb9.png">

**Comment by jasonLaster** [comment] 2020-06-21 03:33
Yes! thanks for filing, i've been meaning to fix this

**Comment by jasonLaster** [comment] 2020-06-21 04:01
duplicate of #95

**Closed by jasonLaster** 2020-06-21 04:01 UTC
Labels: Viewer, bug
